server:
  port: 8888
  servlet:
    context-path: /

spring:
  #本程序名称，可不用进行配置
  application:
    name: demo

  datasource:
      #连接MySQL
      url: jdbc:mysql://localhost:3306/mydatabase?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: admin
      #driver-class-name: com.mysql.jdbc.Driver

  #redis配置，ip和端口
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379

    # 对于以下redis配置，可直接默认值即可，可在配置文件中不写
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  # rabbitmq基本配置
  rabbitmq:
    # 主机地址
    addresses: 172.96.217.239
    # 端口号
    port: 5672
    username: guest
    password: guest
    # 设置虚拟主机
    virtual-host: /
    # 连接超时间
    connection-timeout: 15000

    # rabbit消费端的配置
    listener:
          simple:
            # 并发数
            concurrency: 5
            # 最大的并发数
            max-concurrency:
            # 是否自动签收 auto--自动签收  manual--手工签收
            acknowledge-mode: manual
            # 限流 --消费端同一时间只接受一条消息
            prefetch: 1

# mybatis配置
mybatis:
  configuration:
   #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
   map-underscore-to-camel-case: true

logging:
  level:
   #打印SQL信息
   com.lm.pag.mapper: debug



