#Setting
logging:
  config: classpath:logback-spring.xml
  level:
      com.springboot.demo: DEBUG
  path: logs

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=UTF8
    username: root
    password: admin

server:
  port: 8888

mybatis:
  type-aliases-package: com.springboot.demo.busi.entity
  mapper-locations: classpath:mapper/**/*.xml


